### PR TITLE
feat(profiler): support performance profiling via pprof

### PR DESCRIPTION
**Pull request by aminya**
## Description

This adds support for performance profiling, allowing for finding bottlenecks and performance optimizations. 

It can be enabled via `profiler` feature and the `bench` build profile.

```shell
cargo build --profile=bench --features=profiler
```
## Motivation and Context

This allows for debugging performance issues such as #767 

## How Has This Been Tested?

I tested on the repo mentioned in #767 

## Screenshots / Logs (if applicable)

This screenshot shows that Git Cliff doesn't have any caching, and it goes over the whole history every time no matter what in the subsequent calls.

git-cliff 3758528088515003613 flamegraph

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by orhun — APPROVED** [review]
Loved this PR, thanks a lot! <3

I cleaned up the implementation in 88f93dd6386fa0782e609ba4b78c68243daf5287, can you take a look and let me know how it looks?

Also, I'm thinking of adding documentation for how to run the profiler. I'm guessing it will be just running `cargo run` with the profiler features, right?

**Comment by orhun** [comment]
Also added a CI step so the profiler reports are downloadable for each run. e.g. https://github.com/orhun/git-cliff/actions/runs/10131242627/artifacts/1748030753

**Comment by aminya** [comment]
The changes look good to me. The CI step would help catching performance regressions in future.

As for the documentation, I recommend the following:

### Performance Profiling

Git-cliff can be built with performance profiling instrumentation, which helps with finding bottlenecks. The profiler can be enabled via the `profiler` feature and the `bench` build profile.

```shell
cargo build --profile=bench --features=profiler
```

**Comment by orhun** [comment]
Awesome, thanks!

**Pull request merged**
