### PR TITLE
feat(config): support placing configuration inside pyproject.toml

### PR DESCRIPTION
**Pull request by radusuciu**
Please see #146 for a description. Also please note that this isn't yet tested on an actual repository though if there's interest I can do that.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Hello @radusuciu, thanks for the contribution! 🐻

> Also please note that this isn't yet tested on an actual repository though if there's interest I can do that.

Can you please do that and post results? I think it should work just fine but let's see if there are any sharp edges.

**Comment by radusuciu** [comment]
Hi, thanks for being open with contributions!

Yes, I will test this on some of my projects and update here.

**Comment by orhun** [comment]
Looking forward to it!

**Comment by radusuciu** [comment]
So I tested with [a small project of mine](https://github.com/radusuciu/traktor_nowplaying) and it works as expected in that it produces the same output given a `--config pyproject.toml` option as when the same configuration is specified in a `cliff.toml`. However, since I don't adhere to conventional commits in that project, for reasons that I don't fully understand my commit messages aren't showing (both with `pyproject.toml` and `cliff.toml`) even though I used the configuration [described in the README](https://github.com/orhun/git-cliff#unconventional). So for that reason, I did not commit a changelog.

I tested with a second repository, this time with the [PDM project](https://github.com/pdm-project/pdm). For my fork, see the following files:
- [the configuration, specified in pyproject.toml](https://github.com/pdm-project/pdm/blob/596e5a9a1f24e65de709e1e97202fc13e773cf7e/pyproject.toml). I chose the Keep-A-Changelog style from your README
- [changelog, as generated with `git-cliff` defaults](https://github.com/pdm-project/pdm/blob/596e5a9a1f24e65de709e1e97202fc13e773cf7e/CHANGELOG_WITH_GIT_CLIFF_DEFAULTS.md)
- [changelog, as generated with `git-cliff --config pyproject.toml`](https://github.com/pdm-project/pdm/blob/596e5a9a1f24e65de709e1e97202fc13e773cf7e/CHANGELOG_WITH_GIT_CLIFF_KEEPACHANGELOG.md)

Though I am not yet very familiar with `git-cliff`, it seems to me that the code in this PR works as intended, though I'm happy to test further if you'd like.

Thanks!

**Review by orhun — APPROVED** [review]
Sounds great. Thank you for the PR and detailed testing! 🐻💖

**Comment by radusuciu** [comment]
Awesome, thank you!

**Pull request merged**
