### PR TITLE
feat(docker): build arm64 images again (#879)

### LINKED ISSUE #879: ARM64 docker images take 6h+ to build
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

https://github.com/orhun/git-cliff/actions/runs/10978847295/job/30482488830

The github action failed to build and push 2.6.0 tag to ghcr.io

The Docker job times out after 360 minutes, as described in the [GitHub documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) 

### Steps To Reproduce

.

### Expected behavior

.

### Screenshots / Logs

_No response_

### Software information

Github action

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LtdSauce**
## Description

Enable the arm64 image creation again in the docker workflow. 

## Motivation and Context

The arm64 image builds were previously disabled because they ran into timeouts.
The cause seemed to be, that cargo-chef accidentally build the dependencies twice. And the second build managed to hit the timeout. This solves this, by no longer using the toolchain specified in rust-toolchain.toml but instead relying on the already installed rust version from the image.

This speeds up the build twice:
- No longer building the dependencies twice
- No longer installing the nightly rust toolchain twice

This should fix #879 and make #888 no longer needed.

## How Has This Been Tested?

I have tested this on my fork by changing the workflow in a way that it only builds but does not push.
In this [commit](https://github.com/LtdSauce/git-cliff/commit/40905f063724af0cc17df90d97d7d3c3ea32bcc8) i removed all unnecessary workflows and made the docker workflow not try to push. The result can be seen [here](https://github.com/LtdSauce/git-cliff/actions/runs/11298528527)

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [ ] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by LtdSauce** [comment]
I hope i did the commit messages correct, if not please advise me how to change them :)

**Comment by LtdSauce** [comment]
Nope that seems like it is comming from somewhere else.

**Comment by LtdSauce** [comment]
As i have seen you pushed commits fixing the clippy lints and the NodeJS checks i rebased my branch on the current main branch. Now all checks should pass :)

**Review by orhun — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
