### PR TITLE
fix(config): set max of `limit_commits` to the number of commits

### PR DESCRIPTION
**Pull request by musikid**
## Description

Fixes a panic which occurs when the commit limit set in the config is greater than the number of commits.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
There seems to be an issue with the formatting. Can you run `rustfmt` and commit the result?

**Comment by musikid** [comment]
Sorry, I forgot to run it after!

**Comment by musikid** [comment]
There is one test failing, but it seems unrelated to the fix.

**Review by orhun — APPROVED** [review]
Neato!

**Pull request merged**
