### PR TITLE
feat(npm): add programmatic API for TypeScript

### LINKED ISSUE #514: bug: GitHub Integration does not work on Windows when running through NodeJS package
**Describe the issue**

When running through a NodeJS installed version of `git-cliff` (`npx git-cliff`) the GitHub integration is not activated/read/executed/similar despite all config being the same between the NodeJS based execution and the Cargo based execution.

This is an issue for the related project [favware/cliff-jumper](https://github.com/favware/cliff-jumper) because I cannot give users access to this awesome new feature until this is resolved.

**To reproduce**

1. Clone https://github.com/favware/cliff-jumper
1. Setup NodeJS and Yarn
1. Run `yarn install` in the repository
1. (Optional): If you want to see the git-cliff command executed add to `src/commands/update-changelog.ts` above line 25 the line
```ts
console.log(`npx git-cliff --tag ${options.tagTemplate} --prepend ./CHANGELOG.md -u -c ./cliff.toml ${githubConfig} ${monoRepoConfig}`);
```
5. Build the TypeScript code with `yarn build`
6. Run the code with `node . --skip-tag`

**Expected behavior**

1. GitHub integration works through the NodeJs based installation as well
4. The CHANGELOG is updated with a version 3.0.0 and the CHANGELOG.md has PR links for the relevant commits, expected markdown:

```md
# [@favware/cliff-jumper@3.0.0](https://github.com/favware/cliff-jumper/compare/@favware/cliff-jumper@2.2.3...@favware/cliff-jumper@3.0.0) - (2024-02-25)

## 🐛 Bug Fixes

- **deps:** Update dependency git-cliff to v2 ([508b7ad](https://github.com/favware/cliff-jumper/commit/508b7adbf04d79e18a51abcd07b6b69c59d142a7)) ([#157](https://github.com/favware/cliff-jumper/pull/157))
  - 💥 **BREAKING CHANGE:** Bumped git-cliff to v2, please see https://github.com/orhun/git-cliff/blob/main/CHANGELOG.md#200---2024-02-19 for their breaking changes
  - 💥 **Co-authored-by:** renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
- **deps:** Update dependency commander to v12 ([dd7684e](https://github.com/favware/cliff-jumper/commit/dd7684e27216d270e859f0e683efae2347602f52)) ([#151](https://github.com/favware/cliff-jumper/pull/151))
- **deps:** Update all non-major dependencies ([411713e](https://github.com/favware/cliff-jumper/commit/411713e4267c1e373e16de7a13d14e329869266e)) ([#148](https://github.com/favware/cliff-jumper/pull/148))
- **deps:** Update all non-major dependencies ([e3ab8b9](https://github.com/favware/cliff-jumper/commit/e3ab8b912480091db3c5056738b28bd23408556f)) ([#144](https://github.com/favware/cliff-jumper/pull/144))
- Make schema use https ([e7104f2](https://github.com/favware/cliff-jumper/commit/e7104f28ca53dc82ddd186687c14d8d86f677d71))

## 🚀 Features

- Add support for `--github-repo` and `--github-token` ([7ec4f9d](https://github.com/favware/cliff-jumper/commit/7ec4f9dde6135008bd8194cf33ef2df0e44b1055))
```

But the actual markdown is notably missing the PR numbers:
```md
# [@favware/cliff-jumper@3.0.0](https://github.com/favware/cliff-jumper/compare/@favware/cliff-jumper@2.2.3...@favware/cliff-jumper@3.0.0) - (2024-02-25)

## 🐛 Bug Fixes

- **deps:** Update dependency git-cliff to v2 ([508b7ad](https://github.com/favware/cliff-jumper/commit/508b7adbf04d79e18a51abcd07b6b69c59d142a7))
  - 💥 **BREAKING CHANGE:** Bumped git-cliff to v2, please see https://github.com/orhun/git-cliff/blob/main/CHANGELOG.md#200---2024-02-19 for their breaking changes
  - 💥 **Co-authored-by:** renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
- **deps:** Update dependency commander to v12 ([dd7684e](https://github.com/favware/cliff-jumper/commit/dd7684e27216d270e859f0e683efae2347602f52))
- **deps:** Update all non-major dependencies ([411713e](https://github.com/favware/cliff-jumper/commit/411713e4267c1e373e16de7a13d14e329869266e))
- **deps:** Update all non-major dependencies ([e3ab8b9](https://github.com/favware/cliff-jumper/commit/e3ab8b912480091db3c5056738b28bd23408556f))
- Make schema use https ([e7104f2](https://github.com/favware/cliff-jumper/commit/e7104f28ca53dc82ddd186687c14d8d86f677d71))

## 🚀 Features

- Add support for `--github-repo` and `--github-token` ([7ec4f9d](https://github.com/favware/cliff-jumper/commit/7ec4f9dde6135008bd8194cf33ef2df0e44b1055))
```

**Screenshots / Logs**

I ran the commands with `--verbose --debug` so I'll be dumping the logs in collapsed content so this post isn't enormously long

*NodeJS*

<details>
<summary>Click me to expand</summary>

```
$ npx git-cliff --version
git-cliff 2.0.4
```

```
npx git-cliff --tag @favware/cliff-jumper@3.0.0 --prepend ./CHANGELOG.md -u -c ./cliff.toml --github-repo favware/cliff-jumper --github-token $env:GITHUB_TOKEN --verbose --debug
 TRACE git_cliff > Opt {
    help: None,
    version: None,
    verbose: 2,
    init: None,
    config: "./cliff.toml",
    workdir: None,
    repository: None,
    include_path: None,
    exclude_path: None,
    with_commit: None,
    skip_commit: None,
    prepend: Some(
        "./CHANGELOG.md",
    ),
    output: None,
    tag: Some(
        "@favware/cliff-jumper@3.0.0",
    ),
    bump: false,
    bumped_version: false,
    body: None,
    latest: false,
    current: false,
    unreleased: true,
    topo_order: false,
    no_exec: false,
    context: false,
    strip: None,
    sort: Newest,
    range: None,
    github_token: Some(
        "le token hmm",
    ),
    github_repo: Some(
        RemoteValue(
            Remote {
                owner: "favware",
                repo: "cliff-jumper",
                token: None,
            },
        ),
    ),
}
 TRACE git_cliff > Config {
    changelog: ChangelogConfig {
        header: Some(
            "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n",
        ),
        body: Some(
            "{%- macro remote_url() -%}\n  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\n{%- endmacro -%}\n{% if version %}# [{{ version | trim_start_matches(pat=\"v\") }}]{% if previous %}{% if previous.version %}({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}){% else %}({{ self::remote_url() }}/tree/{{ version }}){% endif %}{% endif %} - ({{ timestamp | date(format=\"%Y-%m-%d\") }})\n{% else %}# [unreleased]\n{% endif %}{% for group, commits in commits | group_by(attribute=\"group\") %}\n    ## {{ group | upper_first }}\n    {% for commit in commits %}\n\t\t- {% if commit.scope %}**{{commit.scope}}:** {% endif %}{{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end=\"\") }}]({{ self::remote_url() }}/commit/{{ commit.id }})){% if commit.github.pr_number %} ([#{{ commit.github.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.github.pr_number }})) {%- endif %}{% if commit.breaking %}{% for breakingChange in commit.footers %}\n{% raw %}  {% endraw %}- 💥 **{{ breakingChange.token }}{{ breakingChange.separator }}** {{ breakingChange.value }}{% endfor %}{% endif %}{% endfor %}\n{% endfor %}\n\n",
        ),
        footer: None,
        trim: Some(
            true,
        ),
        postprocessors: None,
    },
    git: GitConfig {
        conventional_commits: Some(
            true,
        ),
        filter_unconventional: Some(
            true,
        ),
        split_commits: None,
        commit_preprocessors: Some(
            [
                TextProcessor {
                    pattern: Regex(
                        "\\s\\((\\w+\\s)?#([0-9]+)\\)",
                    ),
                    replace: Some(
                        "",
                    ),
                    replace_command: None,
                },
            ],
        ),
        commit_parsers: Some(
            [
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^feat",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🚀 Features",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^fix",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🐛 Bug Fixes",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^docs",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "📝 Documentation",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^perf",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🏃 Performance",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^refactor",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🏠 Refactor",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^typings",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "⌨\u{fe0f} Typings",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^types",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "⌨\u{fe0f} Typings",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            ".*deprecated",
                        ),
                    ),
                    body: Some(
                        Regex(
                            ".*deprecated",
                        ),
                    ),
                    group: Some(
                        "🚨 Deprecation",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^revert",
                        ),
                    ),
                    body: None,
                    group: None,
                    default_scope: None,
                    scope: None,
                    skip: Some(
                        true,
                    ),
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^style",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🪞 Styling",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^test",
                        ),
                    ),
                    body: None,
                    group: Some(
                        "🧪 Testing",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^chore",
                        ),
                    ),
                    body: None,
                    group: None,
                    default_scope: None,
                    scope: None,
                    skip: Some(
                        true,
                    ),
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^ci",
                        ),
                    ),
                    body: None,
                    group: None,
                    default_scope: None,
                    scope: None,
                    skip: Some(
                        true,
                    ),
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: Some(
                        Regex(
                            "^build",
                        ),
                    ),
                    body: None,
                    group: None,
                    default_scope: None,
                    scope: None,
                    skip: Some(
                        true,
                    ),
                    field: None,
                    pattern: None,
                },
                CommitParser {
                    sha: None,
                    message: None,
                    body: Some(
                        Regex(
                            ".*security",
                        ),
                    ),
                    group: Some(
                        "🛡\u{fe0f} Security",
                    ),
                    default_scope: None,
                    scope: None,
                    skip: None,
                    field: None,
                    pattern: None,
                },
            ],
        ),
        protect_breaking_commits: None,
        link_parsers: None,
        filter_commits: Some(
            true,
        ),
        tag_pattern: Some(
            Regex(
                "@favware/cliff-jumper@[0-9]*",
            ),
        ),
        skip_tags: None,
        ignore_tags: Some(
            Regex(
                "",
            ),
        ),
        topo_order: Some(
            false,
        ),
        sort_commits: Some(
            "newest",
        ),
        limit_commits: None,
    },
    remote: RemoteConfig {
        github: Remote {
            owner: "favware",
            repo: "cliff-jumper",
            token: Some(
                Secret([REDACTED alloc::string::String]),
            ),
        },
    },
}
 DEBUG git_cliff_core::changelog > Processing the commits...
 TRACE git_cliff_core::changelog > 432eba4 - Grouping error: `Skipping commit` (chore: update cliff toml)
 TRACE git_cliff_core::changelog > dc7a494 - Grouping error: `Skipping commit` (chore: update cliff jumper config)
 TRACE git_cliff_core::changelog > d2539e7 - Grouping error: `Skipping commit` (chore: update git cliff config to use new config options)
 TRACE git_cliff_core::changelog > e1ead5c - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 33c32cc - Grouping error: `Skipping commit` (chore(deps): update typescript-eslint monorepo to v7 (major) (#155))
 TRACE git_cliff_core::changelog > f953974 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 397386b - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 04d83db - Grouping error: `Skipping commit` (chore(deps): update dependency prettier to ^3.2.5)
 TRACE git_cliff_core::changelog > 933c608 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > b8de0b1 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > be83092 - Grouping error: `Skipping commit` (chore: update renovate and labelsync config)
 TRACE git_cliff_core::changelog > 0070c74 - Grouping error: `Skipping commit` (chore(deps): update dependency prettier to ^3.2.2)
 TRACE git_cliff_core::changelog > c1c5805 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 6747359 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 30a1c63 - Grouping error: `Skipping commit` (chore(deps): update dependency eslint-plugin-prettier to ^5.1.2)
 TRACE git_cliff_core::changelog > f0b9950 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > dd3e3c9 - Grouping error: `Skipping commit` (chore(deps): update actions/setup-node action to v4 (#138))
 TRACE git_cliff_core::changelog > be48dfb - Grouping error: `Skipping commit` (chore(deps): update actions/checkout action to v4 (#137))
 TRACE git_cliff_core::changelog > e8e5394 - Grouping error: `Skipping commit` (chore(deps): update github/codeql-action action to v3 (#141))
 TRACE git_cliff_core::changelog > ed40b4b - Grouping error: `Skipping commit` (chore(deps): update crazy-max/ghaction-github-labeler action to v5 (#139))
 TRACE git_cliff_core::changelog > a9fc490 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > b38abc6 - Grouping error: `Skipping commit` (chore(deps): update dependency prettier to ^3.1.1)
 TRACE git_cliff_core::changelog > b357cdd - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > cd6a97e - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 769bc89 - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 TRACE git_cliff_core::changelog > 9ccecdb - Grouping error: `Skipping commit` (chore(deps): update all non-major dependencies)
 DEBUG git_cliff_core::changelog > Processing the releases...
 DEBUG git_cliff_core::changelog > Generating changelog and prepending...
 DEBUG git_cliff_core::changelog > Generating changelog...
 DEBUG git_cliff_core::changelog > Generating changelog...
# Changelog

All notable changes to this project will be documented in this file.

# [@favware/cliff-jumper@3.0.0](https://github.com/favware/cliff-jumper/compare/@favware/cliff-jumper@2.2.3...@favware/cliff-jumper@3.0.0) - (2024-02-25)

## 🐛 Bug Fixes

- **deps:** Update dependency git-cliff to v2 ([508b7ad](https://github.com/favware/cliff-jumper/commit/508b7adbf04d79e18a51abcd07b6b69c59d142a7))
  - 💥 **BREAKING CHANGE:** Bumped git-cliff to v2, please see https://github.com/orhun/git-cliff/blob/main/CHANGELOG.md#200---2024-02-19 for their breaking changes
  - 💥 **Co-authored-by:** renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
- **deps:** Update dependency commander to v12 ([dd7684e](https://github.com/favware/cliff-jumper/commit/dd7684e27216d270e859f0e683efae2347602f52))
- **deps:** Update all non-major dependencies ([411713e](https://github.com/favware/cliff-jumper/commit/411713e4267c1e373e16de7a13d14e329869266e))
- **deps:** Update all non-major dependencies ([e3ab8b9](https://github.com/favware/cliff-jumper/commit/e3ab8b912480091db3c5056738b28bd23408556f))
- Make schema use https ([e7104f2](https://github.com/favware/cliff-jumper/commit/e7104f28ca53dc82ddd186687c14d8d86f677d71))

## 🚀 Features

- Add support for `--github-repo` and `--github-token` ([7ec4f9d](https://github.com/favware/cliff-jumper/commit/7ec4f9dde6135008bd8194cf33ef2df0e44b1055))
```

</details>

*Cargo*

<details>
<summary>Click me to expand</summary>

```
$ git cliff --version
git-cliff 2.0.4
```

for logs see this log file, it's 10 MB after enabling `--verbose --debug`: [log.txt](https://github.com/orhun/git-cliff/files/14396339/log.txt)

</details>

**Software information**

- Operating system: Windows 11 10.0.22631
- Rust version: rustc 1.76.0 (07dca489a 2024-02-04)
- Project version: 2.0.4
- Node: 20.11.0
- npm: 10.2.4
- Yarn: 4.1.0

**Additional context**

### PR DESCRIPTION
**Pull request by favna**
## Description

Working on cliff-jumper it irked me that I had to call git-cliff through `npx`. Looking at the code I figured I could easily add a small programmatic API on top of (or technically rather below 😂) the CLI one currently provided so here we are.

Other than the actual changes in the source code I also took the liberty to:

1. Update dev dependencies
2. Switch out regular child_process with [execa](https://github.com/sindresorhus/execa), primarily for its promise-based API but also refer to the other advantages it offers (FWIW it's one of many Sindre's packages so it can be trusted to be stable and good)
3. Added [`tsup`](https://github.com/egoist/tsup) as bundler so separate CJS, ESM and CLI bundles can easily be generated
   - The whole split of CJS and ESM is something I could go into a lot more detail for but for brevity's sake I'll just keep it at that the NodeJS ecosystem is currently shattered between the two and for proper TypeScript support 2 bundles have to be provided, related for more reading: https://github.com/arethetypeswrong/arethetypeswrong.github.io
4. Updated from Yarn v1 to Yarn v4
5. Marked the package as being an ES module, thanks to the added export mapping and the split CJS/ESM bundles from point 3 this is now possible. It also allows the source code to use modern ESM code like `import.meta.resolve` instead of the old `require.resolve`, yay!
6. Added the export mapping, it's the modern way in a package.json to define all the entrypoints
7. Modernized the tsconfig, more yay for modern code.

_**Important:**_ This sets the minimum NodeJS requirement to Node 18 as it is the lowest version that supports `import.meta.resolve` _without_ an experimental flag ([docs v16](https://nodejs.org/docs/latest-v16.x/api/esm.html#importmetaresolvespecifier-parent), [docs v18](https://nodejs.org/docs/latest-v18.x/api/esm.html#importmetaresolvespecifier), [docs v20](https://nodejs.org/docs/latest-v20.x/api/esm.html#importmetaresolvespecifier)). In my opinion this is acceptable because [Node 16 has been End of Life since 2023-09-11](https://nodejs.github.io/nodejs.dev/en/about/releases/) and people should as minimum update to Node 18.

## Motivation and Context

Having a programmatic API is always a nice-to-have for the more advanced users of the git-cliff npm package as it allows far easier scripting integration. The primary motivation here is my own library cliff-jumper which is one such "more advanced use".

## How Has This Been Tested?

I have tested this by `yarn link`ing the local repository to my cliff-jumper repository where I then refactored my code to use the programmatic API. Where before I had to parse out the options provided to cliff-jumper to proper CLI options and call npx I can now call the programmatic API. I have ran this code and it works perfectly:
```ts
const gitCliffOptions: GitCliffOptions = {
  tag: options.tagTemplate,
  prepend: './CHANGELOG.md',
  unreleased: true,
  config: './cliff.toml'
};

if (!isNullishOrEmpty(repositoryRootDirectory)) {
  gitCliffOptions.repository = repositoryRootDirectory;
  gitCliffOptions.includePath = `${options.packagePath}/*`;
}

const githubToken = getGitHubToken(options);
const githubRepo = getGitHubRepo(options);
if (!isNullishOrEmpty(githubRepo) && !isNullishOrEmpty(githubToken)) {
  const resolvedGitHubRepo = githubRepo === 'auto' ? `${options.org}/${options.name}` : `${githubRepo}`;

  gitCliffOptions.githubRepo = resolvedGitHubRepo;
  gitCliffOptions.githubToken = githubToken;
}

await runGitCliff(gitCliffOptions);
```

## Screenshots / Logs (if applicable)

N.A.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (no code change)
- [x] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
(I hope so anyway, I had VSCode auto format and it *should* have picked up editorconfig)
- [x] I have updated the documentation accordingly.
- [x] ~~I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).~~ N.A. I haven't touched rust code
- [x] I checked the lints with ~~[clippy](https://github.com/rust-lang/rust-clippy)~~ ESLint.
- [x] ~~I have added tests to cover my changes.~~ N.A.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by favna** [comment]
Tested it on both MacOS and Windows now. Also with a not 3 AM brain which let me to make the last 2 commits lol

**Comment by orhun** [comment]
Hey this looks pretty good! I will test it locally soon.

I can also create a RC release just to test this functionality and see if everything works with NPM.

**Comment by orhun** [comment]
I tried running `yarn` && `yarn dev` inside `npm/git-cliff` directory and got this error:

```
file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/index.js:3
Object.defineProperty(exports, "__esModule", { value: true });
                      ^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/orhun/gh/git-cliff/npm/git-cliff/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/index.js:3:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.0
```

Whereas this was working before like this:

```
$ yarn dev
yarn run v1.22.21
$ yarn build && node lib/index.js
$ tsc
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
```

@favna any idea what's going on?

**Comment by favna** [comment]
@orhun Fixed it. I overlooked the `dev` script calling the cli so I just had to adjust the path.

**Comment by favna** [comment]
Hm I do still get an error but I'm not sure if that's related the programmatic change?

```
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
 ERROR git_cliff > Git error: `could not find repository at 'F:\favware\git-cliff\npm\git-cliff'; class=Repository (6); code=NotFound (-3)`
file:///F:/favware/git-cliff/npm/git-cliff/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: F:\favware\git-cliff\npm\git-cliff\node_modules\git-cliff-windows-x64\bin\git-cliff.exe
    at makeError (file:///F:/favware/git-cliff/npm/git-cliff/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///F:/favware/git-cliff/npm/git-cliff/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///F:/favware/git-cliff/npm/git-cliff/lib/cli/cli.js:60:25) {
  shortMessage: 'Command failed with exit code 1: F:\\favware\\git-cliff\\npm\\git-cliff\\node_modules\\git-cliff-windows-x64\\bin\\git-cliff.exe',
  command: 'F:\\favware\\git-cliff\\npm\\git-cliff\\node_modules\\git-cliff-windows-x64\\bin\\git-cliff.exe',
  escapedCommand: '"F:\\favware\\git-cliff\\npm\\git-cliff\\node_modules\\git-cliff-windows-x64\\bin\\git-cliff.exe"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: 'F:\\favware\\git-cliff\\npm\\git-cliff',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v20.11.0
```

**Comment by orhun** [comment]
I'm getting a different error:

```
file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/cli/cli.js:22
    throw new Error(
          ^

Error: Couldn't find git-cliff binary inside node_modules for linux-x64
    at getExePath (file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/cli/cli.js:22:11)
    at runGitCliff (file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/cli/cli.js:48:25)
    at run (file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/cli/cli.js:60:31)
    at file:///home/orhun/gh/git-cliff/npm/git-cliff/lib/cli/cli.js:64:6
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.0
```

However, I can confirm that the binary exists:

```
$ file node_modules/git-cliff-linux-x64/bin/git-cliff
node_modules/git-cliff-linux-x64/bin/git-cliff: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7bc79cc471a2b79104849701c87fcc2ebcb76add, stripped
```

**Comment by orhun** [comment]
I applied this patch:

```diff
diff --git a/npm/git-cliff/src/getExePath.ts b/npm/git-cliff/src/getExePath.ts
index f1bbbd6..341087f 100644
--- a/npm/git-cliff/src/getExePath.ts
+++ b/npm/git-cliff/src/getExePath.ts
@@ -28,7 +28,7 @@ export async function getExePath() {
     );
   } catch (e) {
     throw new Error(
-      `Couldn't find git-cliff binary inside node_modules for ${os}-${arch}`
+      `Couldn't find git-cliff binary inside node_modules for ${os}-${arch} (${e})`,
     );
   }
 }
```

The error is:

```
Error: Couldn't find git-cliff binary inside node_modules for linux-x64 (TypeError: (intermediate value).resolve is not a function)
```

**Comment by favna** [comment]
> My IDE also complains about the await import.meta.resolve line:
```
typescript: 'await' has no effect on the type of this expression.
```

I was under the impression that `import.meta.resolve` returns a `Promise` but apparently it does not so the IDE was correct here.

I'll see if I can reproduce your issue. So far I've only tried with MacOS and Windows on Node 20. I'll try with Node 18.17.0 (your version as seen above) on both and leverage one of my VPSs for Linux x64 as well. I'll report back.

**Comment by favna** [comment]
|          OS         	|  Arch  	| Node version 	| Result of `import.meta.resolve`                                                                                 	| Result 	|
|:-------------------:	|:------:	|--------------	|-----------------------------------------------------------------------------------------------------------------	|--------	|
|    Windows 11 Pro   	| x86_64 	| v18.17.0     	| TypeError: (intermediate value).resolve is not a function                                                       	|    ❌   	|
|    Windows 11 Pro   	| x86_64 	| v18.19.1     	| file:///F:/favware/git-cliff/npm/git-cliff/node_modules/git-cliff-windows-x64/bin/git-cliff.exe                 	|    ✅   	|
|    Windows 11 Pro   	| x86_64 	| v20.11.1     	| file:///F:/favware/git-cliff/npm/git-cliff/node_modules/git-cliff-windows-x64/bin/git-cliff.exe                 	|    ✅   	|
|        MacOS        	|  arm64 	| v18.17.0     	| TypeError: (intermediate value).resolve is not a function                                                       	|    ❌   	|
|        MacOS        	|  arm64 	| v18.19.1     	| file:///Users/favna/workspace/favware/git-cliff/npm/git-cliff/node_modules/git-cliff-darwin-arm64/bin/git-cliff 	|    ✅   	|
|        MacOS        	|  arm64 	| v20.11.1     	| file:///Users/favna/workspace/favware/git-cliff/npm/git-cliff/node_modules/git-cliff-darwin-arm64/bin/git-cliff 	|    ✅   	|
| Debian GNU/Linux 11 	| x86_64 	| v18.17.0     	| TypeError: (intermediate value).resolve is not a function                                                       	|    ❌   	|
| Debian GNU/Linux 11 	| x86_64 	| v18.19.1     	| file:///root/workspace/git-cliff/npm/git-cliff/node_modules/git-cliff-linux-x64/bin/git-cliff                   	|    ✅   	|
| Debian GNU/Linux 11 	| x86_64 	| v20.11.1     	| file:///root/workspace/git-cliff/npm/git-cliff/node_modules/git-cliff-linux-x64/bin/git-cliff                   	|    ✅   	|

I think the pattern is fairly obvious. Looks like there is a bug in Node 18.17.0 which is fixed by 18.19.1 lol. Turns out you'll just have to update to the latest minor, or go straight to 18 then.

**Comment by orhun** [comment]
Thanks for the debugging this - everything works as expected now after upgrading node!

**Review by orhun — APPROVED** [review]

**Pull request merged**
