### PR TITLE
feat(args): support initialization with built-in templates

### PR DESCRIPTION
**Pull request by orhun**
## Motivation

Now we embed the files under `examples/` into the binary and support the following use cases:

```sh
# creates cliff.toml with keepachangelog template
git cliff --init keepachangelog
```

```sh
# generates a changelog in keepachangelog format
git cliff --config keepachangelog
```

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (no code change)
- [x] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by liuyinz** [comment]
@orhun Briliant work !
how about more options related to built-in templates? e.g.
```sh
# add directory which stores user-defined templates, 
git cliff --templates-dir <PATH> (ENV: GIT_CLIFF_TEMPLATES_DIR=)

# print all available templates, both built-in and user-defined templates, which is needed for providing completion in emacs.
 git cliff --list-templates
```
these features are implemented in my emacs plugin for now and glad for more features are supported natively.

**Comment by orhun** [comment]
@liuyinz thank you! Those are great suggestions.

Would you be potentially interested in contributing this? Either way, I would appreciate a tracking issue to implement them in the future.

**Comment by liuyinz** [comment]
@orhun I know nothing about rust.. so waiting :>

**Comment by orhun** [comment]
Can you at least create an issue so that I won't forget about this feature? :D

**Pull request merged**
