### PR TITLE
feat(args): update clap and clap extras to v4

### LINKED ISSUE #125: Update clap to v4
**Is your feature request related to a problem? Please describe.**

```sh
$ cargo outdated
git-cliff
================
Name           Project  Compat  Latest  Kind    Platform
----           -------  ------  ------  ----    --------
clap           3.2.23   ---     4.0.26  Normal  ---
clap_complete  3.2.5    ---     4.0.5   Normal  ---
clap_mangen    0.1.11   ---     0.2.4   Normal  ---
```

**Describe the solution you'd like**
Update `clap`, `clap_complete` and `clap_mangen` to the latest version.

**Describe alternatives you've considered**
None.

**Additional context**
Changelog: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#400---2022-09-28

### PR DESCRIPTION
**Pull request by lbowenwest**
## Description

Update clap version to v4 latest, as well as clap_complete and clap_mangen to the latest versions

## Motivation and Context

Closes #125 

## How Has This Been Tested?

Running the help and version commands locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [x] Other: dependency update

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Hi, thanks for your contribution! 🐻

> ## How Has This Been Tested?
> 
> Running the help and version commands locally

Can you do a more through test with running the other commands as well?

Also, can you update README.md and other parts of the codebase (if necessary) accordingly?

**Comment by lbowenwest** [comment]
Yeah sure I ran through the rest of the example commands in the readme, and they all seemed to work! 

I tried to keep it unchanged, from an outside perspective, so I don't think there needs to be any updates to the readme, and I think I got all the references to previous clap versions in the rest of the codebase.

**Comment by lbowenwest** [comment]
hey @orhun is there anything else you need me to do for this?

**Comment by orhun** [comment]
Hello @lbowenwest, sorry I was a bit busy and couldn't review this PR. I think we're ready to go if you update `README.md` as well.

**Comment by lbowenwest** [comment]
No worries, what about the readme do you want me to update? All the options should be the same.

**Comment by orhun** [comment]
I thought the new version of `clap` changed the style of the help text. If it's not, then it's all good. I will review & merge this soon if everything goes well with my tests!

**Comment by alerque** [comment]
The formatting changed (color was dropped, headings got different capitalization, etc.) but since the README doesn't show full `--help` output only excerpts those bits may not actually have changed.

**Review by orhun — APPROVED** [review]
Great, TYSM! 🐻

**Pull request merged**
