### PR TITLE
feat(bitbucket): support self-hosted instances

### LINKED ISSUE #762: Bitbucket integration not working with self-hosted instance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The Bitbucket integration mentions that the API endpoint can be changed with a env var, but that won't work as self-hosted instances use a completely different REST API compared to the cloud version.

It seems Atlassian splits the APIs between Cloud and Server (self-hosted). Definitely the Cloud version looks much more like a newer and simple API, so I guess they kept the old API for self-hosted instances for backward compatibility.

Therefore, a dedicated extra remote is needed that can handle the older API.

I already prepared the changes locally, but wanted to create an issue for it as well so it can be tracked an associated later.

### Steps To Reproduce

1. Have a self-hosted instance of Bitbucket
2. Create project
3. Run git-cliff with the repo configured for the `bitbucket` integration
4. All API requests fail

### Expected behavior

The API requests should work as expected and git-cliff associate the PRs with commits.

### Screenshots / Logs

_No response_

### Software information

- Operating system: Arch Linux
- Rust version: 1.79.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dnaka91**
Atlassian has different APIs for the _Cloud_ and _Server_ (self-hosted)
version of Bitbucket. Therefore, a dedicated remote is needed to handle
the self-hosted version.

## Motivation and Context

closes #762 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by orhun — COMMENTED** [review]
LGTM overall, I'm thinking if we should merge this functionality with the `bitbucket` feature and use the cloud API whenever a custom bitbucket URL is provided. I think it will make things more clean, what do you think?

Also sorry for the delay. I'm totally happy to proceed with this PR and I hope you're planning to work on it 🐻

**Comment by dnaka91** [comment]
@orhun absolutely I'll continue on it. Just haven't have much time lately to continue on where I started.

I really like the idea of switching the implementation based on whether a custom URI was used. Felt really odd to have these two configs despite they pretty much achieving the same.

A few things are obviously still missing here and there. Especially testing is an issue I guess.

To have a self-hosted Bitbucket server _running_ is easy as you can just grab the latest Docker image and run it, but then you need to get a 30-day license and so on. Way too many steps to verify the implementation.

As far as I understand the API isn't really evolving much (maybe the server variant gets the update to API v2 at some point eventually). So my idea is to record a few queries and save them in the repo, anonymized of course. Then we can see if we use a full blown HTTP mocking crate or simply deserialize the files into expected responses.
That way we can at least verify the implementation to some degree without having to run a full server every time. Might be a good solution for the other backends as well.

**Comment by orhun** [comment]
> absolutely I'll continue on it. Just haven't have much time lately to continue on where I started.

Thanks for showing interest! Just an idea, maybe it makes sense to start this PR over since we won't have two separate functionalities for this :)

> To have a self-hosted Bitbucket server running is easy as you can just grab the latest Docker image and run it, but then you need to get a 30-day license and so on. Way too many steps to verify the implementation.

Wow, that's really bad ;/

> So my idea is to record a few queries and save them in the repo, anonymized of course. Then we can see if we use a full blown HTTP mocking crate or simply deserialize the files into expected responses. That way we can at least verify the implementation to some degree without having to run a full server every time. Might be a good solution for the other backends as well.

Loved this idea! This will also save us from spurious CI errors due to networking issues that happen occasionally with GitLab etc.

Would love to have this in!

**Comment by dnaka91** [comment]
No need to start it over, we can use the power of rebase and force pushes :wink:. But it's basically somewhat of a start over, haha.

First step done, now the Bitbucket implementation picks the Cloud or Server variant based on whether a custom API URL is set.

Will get to add in some tests and finish up some missing docs (clippy will probably fail) next.

**Comment by orhun** [comment]
Perfect!

**Comment by orhun** [comment]
Just lmk when this is ready for review :)

**Comment by dnaka91** [comment]
Just a small heads up, I didn't forget about the PR. Priorities are quite somewhere else at the moment, so I simply didn't get to pull over and sanitize those request/response samples.

But I'm sure I'll get to it sometime.

**Comment by orhun** [comment]
No worries, sounds good :)

**Comment by orhun** [comment]
Hey, lost interest? :) (it's totally fine)

**Comment by dnaka91** [comment]
Hey, sorry for that. I should have probably written a comment first and then closed the PR (actually auto-closed due to deleting the branch).

This was mostly for work and the priority on it was pretty low. Plus the latest changes made a rebase pretty hard, and I forgot half of my PR changes as well because I haven't touched it in a long time.

So I figured it's best to close this for now and then rather make a fresh PR from scratch with the missing bits included, that we discussed here so far.

**Pull request closed without merging**
