### PR TITLE
feat(args): update clap to v4

### PR DESCRIPTION
**Pull request by Jehan-h20220012**
## Description

The clap version is being updated to v4 as required.
## Motivation and Context

This change was required as the clap version was asked to be changed in the issue #125  

#125 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ x] Other Updation for clap version to v4

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Jehan-h20220012** [comment]
Please approve mt PR

**Comment by orhun** [comment]
@Jehan-h20220012 please fix the CI.

**Comment by Jehan-h20220012** [comment]
@orhun can you please guide me what to do for it!

**Comment by Jehan-h20220012** [comment]
Hi I have added the changes can you check and let me know if there is any issues.

**Comment by orhun** [comment]
Have you manually tested the functionality of each argument?

P.S. There seems to be a formatting issue. Please run `cargo fmt` and commit changes.

**Comment by Jehan-h20220012** [comment]
@orhun I am referring other projects where they have updated the version to clap v4 and raising the pull request.I am a beginner and I have tried my level best to find references and close this issue.Please guide me with the changes so that I can merge the pull request and close this issue succesfully.

**Comment by orhun** [comment]
> @orhun I am referring other projects where they have updated the version to clap v4 and raising the pull request.I am a beginner and I have tried my level best to find references and close this issue.Please guide me with the changes so that I can merge the pull request and close this issue succesfully.

You can check out the contribution guidelines: https://github.com/orhun/git-cliff/blob/main/CONTRIBUTING.md

It includes the necessary information about building, formatting and checking lints.

I might step in and help with the rest of this pull request soon.

**Comment by orhun** [comment]
@Jehan-h20220012 let's suspend this PR/issue until you fix issues on your [fork](https://github.com/Jehan-h20220012/git-cliff/tree/cargo_fix) or somebody else steps in.

**Pull request closed without merging**
