### PR TITLE
feat(ci): test that python wheels can be built and installed

### PR DESCRIPTION
**Pull request by radusuciu**
## Description

This adds a CI job that builds and installs python wheels for every platform that wheels are published to PyPI.

## Motivation and Context

This should warn against issues such as #534.

## How Has This Been Tested?

Please refer to GHA runs of this workflow in my fork: https://github.com/radusuciu/git-cliff/actions/workflows/ci.yml

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [ ] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by radusuciu** [comment]
It almost works:

https://github.com/radusuciu/git-cliff/actions/runs/8207985679/

The platforms that fail. fail because of the same reason:

```
Defaulting to user installation because normal site-packages is not writeable
Looking in links: pypi/wheels
Processing ./pypi/wheels/git_cliff-2.1.2.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in links: pypi/wheels
      ERROR: Could not find a version that satisfies the requirement maturin<2,>=1.5 (from versions: none)
      ERROR: No matching distribution found for maturin<2,>=1.5
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

Relevant line:

```
ERROR: Could not find a version that satisfies the requirement maturin<2,>=1.5 (from versions: none)
```

I think this may be because maturin isn't available for all of the same platforms that are listed in the matrix here. In any case, I think we don't actually need maturin to be installed.. I'll need to experiment with this more later, but I think this is a good base.

**Comment by orhun** [comment]
Yup, the workflow looks good. Let's see if we need maturin installed. Also, do you think it is a good idea to test it for all the targets or testing it for each platform (Linux/MacOS/Windows) is enough?

**Comment by radusuciu** [comment]
> Yup, the workflow looks good. Let's see if we need maturin installed. Also, do you think it is a good idea to test it for all the targets or testing it for each platform (Linux/MacOS/Windows) is enough?

I'm not sure, it does seem like testing each platform is overkill. Maybe we can check out what other rust projects that use maturin are doing?

**Comment by orhun** [comment]
Yeah, I agree. Checking out other projects is definitely a good idea.

**Comment by orhun** [comment]
I [looked around](https://github.com/search?q=maturin-action&type=code&p=2) in GitHub a bit and some projects build for each target and some projects just test the platform. I think we can have this check running for each platform as well.

**Comment by davidhewitt** [comment]
Whenever you see the line

> Processing ./pypi/wheels/git_cliff-2.1.2.tar.gz

It means that the wheel wasn't installable on the platform you're testing on, probably because you built for a different platform than the host interpreter running on GitHub actions. As a result, CI is trying to extract the source tarball and build it. You can prevent this fallback with `--only-binary` flag to pip if I recall correctly. Might be worth adding that flag given you're trying to check the wheel.

To match the python to test on to the wheel, you might have to use something like https://github.com/uraimo/run-on-arch-action to run your tests.

**Comment by radusuciu** [comment]
> Whenever you see the line
> 
> > Processing ./pypi/wheels/git_cliff-2.1.2.tar.gz
> 
> It means that the wheel wasn't installable on the platform you're testing on, probably because you built for a different platform than the host interpreter running on GitHub actions. As a result, CI is trying to extract the source tarball and build it. You can prevent this fallback with `--only-binary` flag to pip if I recall correctly. Might be worth adding that flag given you're trying to check the wheel.
> 
> To match the python to test on to the wheel, you might have to use something like https://github.com/uraimo/run-on-arch-action to run your tests.

Thanks @davidhewitt for that insight! I think we can fix that up.

**Comment by orhun** [comment]
Any chance that we get this done before the next release? 😊 @radusuciu

**Comment by orhun** [comment]
Closing due to inactivity. Feel free to come back to this later :)

**Pull request closed without merging**
